### ISSUE TITLE
**Issue Title:** Implementing a Responsive Design for Navigation Menu

### ISSUE THREAD

**Issue by YegorCherov** [YegorCherov/UI#1]
**Body:**

As we continue to enhance the user experience of our application, I'd like to bring up a concern regarding the navigation menu's responsiveness on smaller screen sizes. Currently, the menu items are not properly aligned when the viewport width is reduced.

Upon analyzing the code, I noticed that the `.nav-links` class is using `display: flex;` and `justify-content: space-between;`, which works well for larger screens but becomes problematic on smaller screens due to the uneven distribution of menu items. 

Here's an excerpt from the CSS file:
```css
.nav-links {
  display: flex;
  justify-content: space-between;
}
```
To address this issue, I suggest we implement a responsive design using media queries and adjust the layout accordingly. One possible solution is to use a grid system that can adapt to different screen sizes.

Here's an example of how we could modify the CSS to make it more responsive:
```css
@media (max-width: 768px) {
  .nav-links {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    gap: 10px;
  }
}

@media (max-width: 480px) {
  .nav-links {
    display: grid;
    grid-template-columns: 1fr;
  }
}
```
In this example, we're using media queries to target screen sizes below 768px and 480px. For smaller screens, we change the layout to a single-column grid.

Next steps:

* Apply the above CSS changes and test on different devices
* Refactor the HTML structure if necessary to accommodate the new responsive design

Your input and suggestions are welcome!
